#pragma once
// Generated by Nulvex L4D2 Dumper v6
// 2026-09-30 12:49:51

#include <cstdint>

namespace nulvex::interfaces {

namespace client_dll {
    constexpr uint32_t VCLIENTTOOLS001 = 0x5E032E10;
    constexpr uint32_t ClientRenderTargets001 = 0x5E025E78;
    constexpr uint32_t GameMovement001 = 0x5E023CC8;
    constexpr uint32_t VClientPrediction001 = 0x5E012E18;
    constexpr uint32_t VParticleSystemQuery001 = 0x5DF38028;
    constexpr uint32_t IEffects001 = 0x5DF35284;
    constexpr uint32_t ClientAlphaPropertyMgrV001 = 0x5DFB27C4;
    constexpr uint32_t ClientLeafSystem002 = 0x5DFB27B8;
    constexpr uint32_t VClientEntityList003 = 0x5DFAA574;
    constexpr uint32_t VCLIENTMATERIALSYSTEM001 = 0x5DF24ABC;
    constexpr uint32_t VClient016 = 0x5DF24A98;
    constexpr uint32_t VClientDllSharedAppSystems001 = 0x5DF24A60;
    constexpr uint32_t GameClientExports001 = 0x5DF24A5C;
}

namespace engine_dll {
    constexpr uint32_t VEngineVGui001 = 0x71494B48;
    constexpr uint32_t VSERVERENGINETOOLS001 = 0x71494570;
    constexpr uint32_t VCLIENTENGINETOOLS001 = 0x7149456C;
    constexpr uint32_t VTOOLFRAMEWORKVERSION002 = 0x71494530;
    constexpr uint32_t VENGINETOOLFRAMEWORK003 = 0x71494260;
    constexpr uint32_t VENGINETOOL003 = 0x71494260;
    constexpr uint32_t XboxSystemInterface001 = 0x714941C8;
    constexpr uint32_t VWorkshop001 = 0x7171E9F0;
    constexpr uint32_t VProfExport001 = 0x71493DD8;
    constexpr uint32_t VoiceServer002 = 0x71493DB8;
    constexpr uint32_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x71493764;
    constexpr uint32_t VENGINE_HLDS_API_VERSION002 = 0x71493758;
    constexpr uint32_t VENGINE_LAUNCHER_API_VERSION004 = 0x71493728;
    constexpr uint32_t StaticPropMgrServer002 = 0x714933C0;
    constexpr uint32_t StaticPropMgrClient005 = 0x714933BC;
    constexpr uint32_t SpatialPartition001 = 0x71716348;
    constexpr uint32_t VEngineRandom001 = 0x71492FD4;
    constexpr uint32_t VEngineServerStringTable001 = 0x71713A20;
    constexpr uint32_t VEngineClientStringTable001 = 0x717139A8;
    constexpr uint32_t INETSUPPORT_001 = 0x71492514;
    constexpr uint32_t VModelInfoClient004 = 0x71492248;
    constexpr uint32_t VModelInfoServer002 = 0x71492244;
    constexpr uint32_t GAMEEVENTSMANAGER001 = 0x7148FDE8;
    constexpr uint32_t GAMEEVENTSMANAGER002 = 0x716F5400;
    constexpr uint32_t EngineTraceClient003 = 0x7148FA5C;
    constexpr uint32_t EngineTraceServer003 = 0x7148FA40;
    constexpr uint32_t VCvarQuery001 = 0x7148AD74;
    constexpr uint32_t BlackBoxVersion001 = 0x7148A5B0;
    constexpr uint32_t VEngineServer022 = 0x7148A4FC;
    constexpr uint32_t ServerUploadGameStats001 = 0x7148A498;
    constexpr uint32_t GameServerData001 = 0x7148A1D8;
    constexpr uint32_t ISERVERPLUGINHELPERS001 = 0x714893F8;
    constexpr uint32_t VEngineRenderView013 = 0x71488F6C;
    constexpr uint32_t VEngineShadowMgr002 = 0x7168AB40;
    constexpr uint32_t VEngineEffects001 = 0x71488B4C;
    constexpr uint32_t VEngineModel016 = 0x71664248;
    constexpr uint32_t VPhysicsDebugOverlay001 = 0x714874F4;
    constexpr uint32_t VDebugOverlay003 = 0x714874F0;
    constexpr uint32_t VEngineClient013 = 0x71485504;
    constexpr uint32_t IEngineSoundServer003 = 0x71483160;
    constexpr uint32_t IEngineSoundClient003 = 0x714830C8;
}

namespace inputsystem_dll {
    constexpr uint32_t InputSystemVersion001 = 0x749DBE50;
}

namespace materialsystem_dll {
    // ShaderDLL004 = NULL (not instantiated)
    constexpr uint32_t ShaderSystem002 = 0x749783BC;
    constexpr uint32_t VMaterialSystemStub001 = 0x74977F70;
    constexpr uint32_t VEngineCvar007 = 0x74A7C0D0;
    constexpr uint32_t MaterialSystemHardwareConfig013 = 0x72CD90B0;
    constexpr uint32_t VMaterialSystemConfig004 = 0x749737C0;
    constexpr uint32_t VMaterialSystem080 = 0x7497C278;
    constexpr uint32_t COLORCORRECTION_VERSION_1 = 0x7497301C;
}

namespace server_dll {
    constexpr uint32_t VSERVERTOOLS001 = 0x5D696A08;
    constexpr uint32_t ServerGameTags001 = 0x5D693DA0;
    constexpr uint32_t GameMovement001 = 0x5D71CED8;
    constexpr uint32_t HLTVDirector001 = 0x5D707568;
    constexpr uint32_t PluginHelpersCheck001 = 0x5D6539F4;
    constexpr uint32_t BotManager001 = 0x5D6529C4;
    constexpr uint32_t PlayerInfoManager002 = 0x5D6529C0;
    constexpr uint32_t PlayerInfoManager001 = 0x5D6529C8;
    constexpr uint32_t VServerDllSharedAppSystems001 = 0x5D63E3B0;
    constexpr uint32_t ServerGameClients003 = 0x5D63E3AC;
    constexpr uint32_t ServerGameEnts001 = 0x5D63E3A8;
    constexpr uint32_t ServerGameDLL005 = 0x5D63E398;
    constexpr uint32_t IEffects001 = 0x5D62E064;
}

namespace studiorender_dll {
    constexpr uint32_t VStudioRender026 = 0x74687018;
}

namespace vguimatsurface_dll {
    constexpr uint32_t VGUI_Surface031 = 0x72EA8560;
}

namespace vphysics_dll {
    constexpr uint32_t VPhysicsSurfaceProps001 = 0x7308BB98;
    constexpr uint32_t VPhysicsCollision007 = 0x7307D24C;
    // Physics2_Interface_v0_4 = NULL (not instantiated)
    // Physics2_Interface_v0_3 = NULL (not instantiated)
    // Physics2_Disabler_Interface_v1 = NULL (not instantiated)
    // Physics2_Interface_v0_5 = NULL (not instantiated)
    constexpr uint32_t VPhysics031 = 0x7307D1CC;
}

namespace vstdlib_dll {
    constexpr uint32_t VProcessUtils001 = 0x74A7A6E0;
    constexpr uint32_t VEngineCvar007 = 0x74A7C0D0;
}

} // namespace nulvex::interfaces
