#pragma once
// Generated by Nulvex L4D2 Dumper v11
// 2026-10-01 09:49:47

// Absolute addresses are valid only for the sampled process; use RVAs after a restart.

#include <cstdint>

namespace nulvex::dump {

namespace client_dll {
    constexpr uint32_t dwBase = 0x5D860000; // constant | module base address
    constexpr uint32_t dwSize = 0x963000; // constant | module size
    constexpr uint32_t dwEntityList = 0x5DFAA574; // exact_interface | VClientEntityList003 interface ptr
    constexpr uint32_t rvaEntityList = 0x74A574;
    constexpr uint32_t dwClientDll = 0x5DF24A98; // exact_interface | VClient016 interface ptr
    constexpr uint32_t rvaClientDll = 0x6C4A98;
    constexpr uint32_t dwGetAllClasses = 0x5D908A40; // runtime_validated | selected after full ClientClass traversal
    constexpr uint32_t rvaGetAllClasses = 0xA8A40;
    constexpr uint32_t nClient_GetAllClasses = 0x7; // runtime_validated | selected after full ClientClass traversal
    constexpr uint32_t dwClientClassHead = 0x5DF9A4D4; // runtime_validated | ClientClass linked list
    constexpr uint32_t rvaClientClassHead = 0x73A4D4;
    constexpr int32_t  dwEntityArrayOffset = -65552; // runtime_validated | probe confirmed (internal disasm match)
    constexpr uint32_t nEntityStride = 0x10; // source_verified | CEntInfo: IHandleEntity*(+0) serial(+4) prev(+8) next(+C) = 16 bytes
    constexpr uint32_t nEntList_GetClientEntity = 0x3; // exact_interface | vtable index
    constexpr uint32_t nEntity_IClientNetworkable = 0x8; // source_verified | MSVC MI: IClientUnknown(+0) IClientRenderable(+4) IClientNetworkable(+8)
    constexpr uint32_t nNetworkable_GetClientClass = 0x2; // source_verified | IClientNetworkable vtbl: GetIClientUnknown(0) Release(1) GetClientClass(2)
    constexpr uint32_t kNumEntEntries = 0x1000; // source_verified | NUM_ENT_ENTRIES from public/const.h (NUM_ENT_ENTRY_BITS=12)
    constexpr uint32_t kMaxEdicts = 0x800; // source_verified | MAX_EDICTS from public/const.h (MAX_EDICT_BITS=11)
    constexpr uint32_t kBaseShift = 0x0; // runtime_validated | probe validated (score=16140, teams=26, hp=6, origins=178, 346 entities)
    constexpr uint32_t kRenderable_GetModel = 0x8; // runtime_validated | probe validated model and version 49 studio header
    constexpr uint32_t kRenderable_SetupBones = 0xD; // runtime_validated | probe checked head matrix near sample survivor origin
    constexpr uint32_t kModelInfo_GetModelExtraData = 0xB; // runtime_validated | probe validated studiohdr_t and bone hierarchy
    constexpr uint32_t kSampleSurvivorHeadBoneIndex = 0x11; // runtime_validated | sample model survivors/survivor_coach.mdl; resolve by name for each model
    constexpr uint32_t kSampleSurvivorBoneCount = 0x51; // runtime_validated | sample model survivors/survivor_coach.mdl; from validated studiohdr_t
}

namespace d3d9_dll {
    constexpr uint32_t dwBase = 0x72A90000; // constant | module base address
    constexpr uint32_t dwSize = 0x171000; // constant | module size
    constexpr uint32_t nReset = 0x10; // source_verified | IDirect3DDevice9::Reset vtable index
    constexpr uint32_t nPresent = 0x11; // source_verified | IDirect3DDevice9::Present vtable index
    constexpr uint32_t nEndScene = 0x2A; // source_verified | IDirect3DDevice9::EndScene vtable index
    constexpr uint32_t nDrawIndexedPrimitive = 0x52; // source_verified | IDirect3DDevice9 COM vtable index
}

namespace engine_dll {
    constexpr uint32_t dwBase = 0x71060000; // constant | module base address
    constexpr uint32_t dwSize = 0x73F000; // constant | module size
    constexpr uint32_t ptrSignonState = 0xF210080; // runtime_validated | IN GAME (>=6)
    constexpr uint32_t ptrClientState = 0xF210018; // runtime_validated | CClientState heap ptr (signon confirmed)
    constexpr uint32_t ptrLocalPlayerSlot = 0xF210040; // runtime_validated | CClientState+0x28 = 1 (stable, heap-based)
    constexpr uint32_t nCsPlayerSlot = 0x28; // runtime_validated | CClientState offset for m_nPlayerSlot
    constexpr uint32_t dwMaxClients = 0x71487CC0; // pattern_matched | ptr, not count
    constexpr uint32_t rvaMaxClients = 0x427CC0;
    constexpr uint32_t dwGlobalVars = 0x710BE7D8; // runtime_validated | CGlobalVarsBase* (struct scan)
    constexpr uint32_t rvaGlobalVars = 0x5E7D8;
    constexpr uint32_t dwViewMatrix = 0x71661F9C; // runtime_validated | VP matrix (view-projection)
    constexpr uint32_t rvaViewMatrix = 0x601F9C;
    constexpr uint32_t dwRenderEngine = 0x71487BC0; // runtime_validated | render engine global ptr (VP matrix chain validated)
    constexpr uint32_t rvaRenderEngine = 0x427BC0;
    constexpr uint32_t nVtblWorldToScreen = 0x25; // exact_interface | vtbl[37] thunk -> render vtbl[13]
    constexpr uint32_t dwConVarHead = 0x71493BA8; // pattern_matched | ConVar linked list head
    constexpr uint32_t rvaConVarHead = 0x433BA8;
    constexpr uint32_t nVtblIsInGame = 0x1A; // exact_interface | VEngineClient vtable index
    constexpr uint32_t nVtblGetScreenSize = 0x5; // exact_interface
    constexpr uint32_t nVtblGetMaxClients = 0x2B; // exact_interface | returns ptr, not count
    constexpr uint32_t nGV_realtime = 0x0; // source_verified | CGlobalVarsBase::realtime (float)
    constexpr uint32_t nGV_framecount = 0x4; // source_verified | CGlobalVarsBase::framecount (int)
    constexpr uint32_t nGV_absoluteframetime = 0x8; // source_verified | CGlobalVarsBase::absoluteframetime (float)
    constexpr uint32_t nGV_curtime = 0xC; // source_verified | CGlobalVarsBase::curtime (float)
    constexpr uint32_t nGV_frametime = 0x10; // source_verified | CGlobalVarsBase::frametime (float)
    constexpr uint32_t nGV_maxClients = 0x14; // source_verified | CGlobalVarsBase::maxClients (int)
    constexpr uint32_t nGV_tickcount = 0x18; // source_verified | CGlobalVarsBase::tickcount (int)
    constexpr uint32_t nGV_interval_per_tick = 0x1C; // source_verified | CGlobalVarsBase::interval_per_tick (float)
    constexpr uint32_t nGV_interpolation_amount = 0x20; // source_verified | CGlobalVarsBase::interpolation_amount (float)
    constexpr uint32_t nGV_simTicksThisFrame = 0x24; // source_verified | CGlobalVarsBase::simTicksThisFrame (int)
    constexpr uint32_t nGV_network_protocol = 0x28; // source_verified | CGlobalVarsBase::network_protocol (int)
}

namespace inputsystem_dll {
    constexpr uint32_t dwBase = 0x749C0000; // constant | module base address
    constexpr uint32_t dwSize = 0x28000; // constant | module size
}

namespace left4dead2_exe {
    constexpr uint32_t dwBase = 0x2E0000; // constant | module base address
    constexpr uint32_t dwSize = 0x5E000; // constant | module size
}

namespace materialsystem_dll {
    constexpr uint32_t dwBase = 0x74880000; // constant | module base address
    constexpr uint32_t dwSize = 0x13D000; // constant | module size
}

namespace server_dll {
    constexpr uint32_t dwBase = 0x5CED0000; // constant | module base address
    constexpr uint32_t dwSize = 0x982000; // constant | module size
}

namespace shaderapidx9_dll {
    constexpr uint32_t dwBase = 0x72C10000; // constant | module base address
    constexpr uint32_t dwSize = 0xFF000; // constant | module size
}

namespace studiorender_dll {
    constexpr uint32_t dwBase = 0x74250000; // constant | module base address
    constexpr uint32_t dwSize = 0x453000; // constant | module size
}

namespace tier0_dll {
    constexpr uint32_t dwBase = 0x74AF0000; // constant | module base address
    constexpr uint32_t dwSize = 0x7C000; // constant | module size
}

namespace vguimatsurface_dll {
    constexpr uint32_t dwBase = 0x72D80000; // constant | module base address
    constexpr uint32_t dwSize = 0x172000; // constant | module size
}

namespace vphysics_dll {
    constexpr uint32_t dwBase = 0x72F00000; // constant | module base address
    constexpr uint32_t dwSize = 0x1B5000; // constant | module size
}

namespace vstdlib_dll {
    constexpr uint32_t dwBase = 0x74A50000; // constant | module base address
    constexpr uint32_t dwSize = 0x9A000; // constant | module size
}

namespace aob {

namespace client_dll {
    constexpr const char* aob_GetAllClasses = "A1 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC CC CC";
    constexpr const char* aob_GetClientEntity = "55 8B EC 8B 45 08 85 C0 78 20 3D ?? ?? ?? ?? 7D 19 05 FF EF FF FF 03 C0 8B 0C C1 85 C9 74 0B 8B 01 8B 50 18 FF D2 5D C2 04 00 33 C0 5D C2 04 00";
}

namespace engine_dll {
    constexpr const char* aob_IsInGame_vtbl26 = "E8 ?? ?? ?? ?? 33 C9 83 78 68 06";
    constexpr const char* aob_GetClientState = "A1 ?? ?? ?? ?? 83 C0 08 C3";
    constexpr const char* aob_GetLocalPlayer_vtbl42 = "A1 ?? ?? ?? ?? 8B 40 ?? C3";
    constexpr const char* aob_GetMaxClients_vtbl43 = "A1 ?? ?? ?? ?? C3";
    constexpr const char* aob_GlobalVars = "04 68 ?? ?? ?? ?? 52 FF D0 85";
    constexpr const char* aob_ViewMatrix_thunk = "8B 0D ?? ?? ?? ?? 8B 01 8B 50 34 FF E2 CC";
    constexpr const char* aob_ViewMatrix_target = "83 B9 ?? ?? ?? ?? 01 7E 17 8B 81 E8 00 00 00 8B";
    constexpr const char* aob_ConVarHead = "8B 0D ?? ?? ?? ?? 85 C9 74 ?? 8B 01 8B 50";
}

} // namespace aob

} // namespace nulvex::dump
