#pragma once
// Generated by Nulvex L4D2 Dumper v11
// 2026-10-01 09:49:47

// Interface pointers are process snapshots; rebase the emitted RVAs on restart.

#include <cstdint>

namespace nulvex::interfaces {

namespace client_dll {
    constexpr uint32_t VCLIENTTOOLS001 = 0x5E032E10;
    constexpr uint32_t rva_VCLIENTTOOLS001 = 0x7D2E10;
    constexpr uint32_t ClientRenderTargets001 = 0x5E025E78;
    constexpr uint32_t rva_ClientRenderTargets001 = 0x7C5E78;
    constexpr uint32_t GameMovement001 = 0x5E023CC8;
    constexpr uint32_t rva_GameMovement001 = 0x7C3CC8;
    constexpr uint32_t VClientPrediction001 = 0x5E012E18;
    constexpr uint32_t rva_VClientPrediction001 = 0x7B2E18;
    constexpr uint32_t VParticleSystemQuery001 = 0x5DF38028;
    constexpr uint32_t rva_VParticleSystemQuery001 = 0x6D8028;
    constexpr uint32_t IEffects001 = 0x5DF35284;
    constexpr uint32_t rva_IEffects001 = 0x6D5284;
    constexpr uint32_t ClientAlphaPropertyMgrV001 = 0x5DFB27C4;
    constexpr uint32_t rva_ClientAlphaPropertyMgrV001 = 0x7527C4;
    constexpr uint32_t ClientLeafSystem002 = 0x5DFB27B8;
    constexpr uint32_t rva_ClientLeafSystem002 = 0x7527B8;
    constexpr uint32_t VClientEntityList003 = 0x5DFAA574;
    constexpr uint32_t rva_VClientEntityList003 = 0x74A574;
    constexpr uint32_t VCLIENTMATERIALSYSTEM001 = 0x5DF24ABC;
    constexpr uint32_t rva_VCLIENTMATERIALSYSTEM001 = 0x6C4ABC;
    constexpr uint32_t VClient016 = 0x5DF24A98;
    constexpr uint32_t rva_VClient016 = 0x6C4A98;
    constexpr uint32_t VClientDllSharedAppSystems001 = 0x5DF24A60;
    constexpr uint32_t rva_VClientDllSharedAppSystems001 = 0x6C4A60;
    constexpr uint32_t GameClientExports001 = 0x5DF24A5C;
    constexpr uint32_t rva_GameClientExports001 = 0x6C4A5C;
}

namespace engine_dll {
    constexpr uint32_t VEngineVGui001 = 0x71494B48;
    constexpr uint32_t rva_VEngineVGui001 = 0x434B48;
    constexpr uint32_t VSERVERENGINETOOLS001 = 0x71494570;
    constexpr uint32_t rva_VSERVERENGINETOOLS001 = 0x434570;
    constexpr uint32_t VCLIENTENGINETOOLS001 = 0x7149456C;
    constexpr uint32_t rva_VCLIENTENGINETOOLS001 = 0x43456C;
    constexpr uint32_t VTOOLFRAMEWORKVERSION002 = 0x71494530;
    constexpr uint32_t rva_VTOOLFRAMEWORKVERSION002 = 0x434530;
    constexpr uint32_t VENGINETOOLFRAMEWORK003 = 0x71494260;
    constexpr uint32_t rva_VENGINETOOLFRAMEWORK003 = 0x434260;
    constexpr uint32_t VENGINETOOL003 = 0x71494260;
    constexpr uint32_t rva_VENGINETOOL003 = 0x434260;
    constexpr uint32_t XboxSystemInterface001 = 0x714941C8;
    constexpr uint32_t rva_XboxSystemInterface001 = 0x4341C8;
    constexpr uint32_t VWorkshop001 = 0x7171E9F0;
    constexpr uint32_t rva_VWorkshop001 = 0x6BE9F0;
    constexpr uint32_t VProfExport001 = 0x71493DD8;
    constexpr uint32_t rva_VProfExport001 = 0x433DD8;
    constexpr uint32_t VoiceServer002 = 0x71493DB8;
    constexpr uint32_t rva_VoiceServer002 = 0x433DB8;
    constexpr uint32_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x71493764;
    constexpr uint32_t rva_VENGINE_GAMEUIFUNCS_VERSION005 = 0x433764;
    constexpr uint32_t VENGINE_HLDS_API_VERSION002 = 0x71493758;
    constexpr uint32_t rva_VENGINE_HLDS_API_VERSION002 = 0x433758;
    constexpr uint32_t VENGINE_LAUNCHER_API_VERSION004 = 0x71493728;
    constexpr uint32_t rva_VENGINE_LAUNCHER_API_VERSION004 = 0x433728;
    constexpr uint32_t StaticPropMgrServer002 = 0x714933C0;
    constexpr uint32_t rva_StaticPropMgrServer002 = 0x4333C0;
    constexpr uint32_t StaticPropMgrClient005 = 0x714933BC;
    constexpr uint32_t rva_StaticPropMgrClient005 = 0x4333BC;
    constexpr uint32_t SpatialPartition001 = 0x71716348;
    constexpr uint32_t rva_SpatialPartition001 = 0x6B6348;
    constexpr uint32_t VEngineRandom001 = 0x71492FD4;
    constexpr uint32_t rva_VEngineRandom001 = 0x432FD4;
    constexpr uint32_t VEngineServerStringTable001 = 0x71713A20;
    constexpr uint32_t rva_VEngineServerStringTable001 = 0x6B3A20;
    constexpr uint32_t VEngineClientStringTable001 = 0x717139A8;
    constexpr uint32_t rva_VEngineClientStringTable001 = 0x6B39A8;
    constexpr uint32_t INETSUPPORT_001 = 0x71492514;
    constexpr uint32_t rva_INETSUPPORT_001 = 0x432514;
    constexpr uint32_t VModelInfoClient004 = 0x71492248;
    constexpr uint32_t rva_VModelInfoClient004 = 0x432248;
    constexpr uint32_t VModelInfoServer002 = 0x71492244;
    constexpr uint32_t rva_VModelInfoServer002 = 0x432244;
    constexpr uint32_t GAMEEVENTSMANAGER001 = 0x7148FDE8;
    constexpr uint32_t rva_GAMEEVENTSMANAGER001 = 0x42FDE8;
    constexpr uint32_t GAMEEVENTSMANAGER002 = 0x716F5400;
    constexpr uint32_t rva_GAMEEVENTSMANAGER002 = 0x695400;
    constexpr uint32_t EngineTraceClient003 = 0x7148FA5C;
    constexpr uint32_t rva_EngineTraceClient003 = 0x42FA5C;
    constexpr uint32_t EngineTraceServer003 = 0x7148FA40;
    constexpr uint32_t rva_EngineTraceServer003 = 0x42FA40;
    constexpr uint32_t VCvarQuery001 = 0x7148AD74;
    constexpr uint32_t rva_VCvarQuery001 = 0x42AD74;
    constexpr uint32_t BlackBoxVersion001 = 0x7148A5B0;
    constexpr uint32_t rva_BlackBoxVersion001 = 0x42A5B0;
    constexpr uint32_t VEngineServer022 = 0x7148A4FC;
    constexpr uint32_t rva_VEngineServer022 = 0x42A4FC;
    constexpr uint32_t ServerUploadGameStats001 = 0x7148A498;
    constexpr uint32_t rva_ServerUploadGameStats001 = 0x42A498;
    constexpr uint32_t GameServerData001 = 0x7148A1D8;
    constexpr uint32_t rva_GameServerData001 = 0x42A1D8;
    constexpr uint32_t ISERVERPLUGINHELPERS001 = 0x714893F8;
    constexpr uint32_t rva_ISERVERPLUGINHELPERS001 = 0x4293F8;
    constexpr uint32_t VEngineRenderView013 = 0x71488F6C;
    constexpr uint32_t rva_VEngineRenderView013 = 0x428F6C;
    constexpr uint32_t VEngineShadowMgr002 = 0x7168AB40;
    constexpr uint32_t rva_VEngineShadowMgr002 = 0x62AB40;
    constexpr uint32_t VEngineEffects001 = 0x71488B4C;
    constexpr uint32_t rva_VEngineEffects001 = 0x428B4C;
    constexpr uint32_t VEngineModel016 = 0x71664248;
    constexpr uint32_t rva_VEngineModel016 = 0x604248;
    constexpr uint32_t VPhysicsDebugOverlay001 = 0x714874F4;
    constexpr uint32_t rva_VPhysicsDebugOverlay001 = 0x4274F4;
    constexpr uint32_t VDebugOverlay003 = 0x714874F0;
    constexpr uint32_t rva_VDebugOverlay003 = 0x4274F0;
    constexpr uint32_t VEngineClient013 = 0x71485504;
    constexpr uint32_t rva_VEngineClient013 = 0x425504;
    constexpr uint32_t IEngineSoundServer003 = 0x71483160;
    constexpr uint32_t rva_IEngineSoundServer003 = 0x423160;
    constexpr uint32_t IEngineSoundClient003 = 0x714830C8;
    constexpr uint32_t rva_IEngineSoundClient003 = 0x4230C8;
}

namespace inputsystem_dll {
    constexpr uint32_t InputSystemVersion001 = 0x749DBE50;
    constexpr uint32_t rva_InputSystemVersion001 = 0x1BE50;
}

namespace materialsystem_dll {
    // ShaderDLL004 = NULL (not instantiated)
    constexpr uint32_t ShaderSystem002 = 0x749783BC;
    constexpr uint32_t rva_ShaderSystem002 = 0xF83BC;
    constexpr uint32_t VMaterialSystemStub001 = 0x74977F70;
    constexpr uint32_t rva_VMaterialSystemStub001 = 0xF7F70;
    constexpr uint32_t VEngineCvar007 = 0x74A7C0D0;
    constexpr uint32_t MaterialSystemHardwareConfig013 = 0x72CD90B0;
    constexpr uint32_t VMaterialSystemConfig004 = 0x749737C0;
    constexpr uint32_t rva_VMaterialSystemConfig004 = 0xF37C0;
    constexpr uint32_t VMaterialSystem080 = 0x7497C278;
    constexpr uint32_t rva_VMaterialSystem080 = 0xFC278;
    constexpr uint32_t COLORCORRECTION_VERSION_1 = 0x7497301C;
    constexpr uint32_t rva_COLORCORRECTION_VERSION_1 = 0xF301C;
}

namespace server_dll {
    constexpr uint32_t VSERVERTOOLS001 = 0x5D696A08;
    constexpr uint32_t rva_VSERVERTOOLS001 = 0x7C6A08;
    constexpr uint32_t ServerGameTags001 = 0x5D693DA0;
    constexpr uint32_t rva_ServerGameTags001 = 0x7C3DA0;
    constexpr uint32_t GameMovement001 = 0x5D71CED8;
    constexpr uint32_t rva_GameMovement001 = 0x84CED8;
    constexpr uint32_t HLTVDirector001 = 0x5D707568;
    constexpr uint32_t rva_HLTVDirector001 = 0x837568;
    constexpr uint32_t PluginHelpersCheck001 = 0x5D6539F4;
    constexpr uint32_t rva_PluginHelpersCheck001 = 0x7839F4;
    constexpr uint32_t BotManager001 = 0x5D6529C4;
    constexpr uint32_t rva_BotManager001 = 0x7829C4;
    constexpr uint32_t PlayerInfoManager002 = 0x5D6529C0;
    constexpr uint32_t rva_PlayerInfoManager002 = 0x7829C0;
    constexpr uint32_t PlayerInfoManager001 = 0x5D6529C8;
    constexpr uint32_t rva_PlayerInfoManager001 = 0x7829C8;
    constexpr uint32_t VServerDllSharedAppSystems001 = 0x5D63E3B0;
    constexpr uint32_t rva_VServerDllSharedAppSystems001 = 0x76E3B0;
    constexpr uint32_t ServerGameClients003 = 0x5D63E3AC;
    constexpr uint32_t rva_ServerGameClients003 = 0x76E3AC;
    constexpr uint32_t ServerGameEnts001 = 0x5D63E3A8;
    constexpr uint32_t rva_ServerGameEnts001 = 0x76E3A8;
    constexpr uint32_t ServerGameDLL005 = 0x5D63E398;
    constexpr uint32_t rva_ServerGameDLL005 = 0x76E398;
    constexpr uint32_t IEffects001 = 0x5D62E064;
    constexpr uint32_t rva_IEffects001 = 0x75E064;
}

namespace studiorender_dll {
    constexpr uint32_t VStudioRender026 = 0x74687018;
    constexpr uint32_t rva_VStudioRender026 = 0x437018;
}

namespace vguimatsurface_dll {
    constexpr uint32_t VGUI_Surface031 = 0x72EA8560;
    constexpr uint32_t rva_VGUI_Surface031 = 0x128560;
}

namespace vphysics_dll {
    constexpr uint32_t VPhysicsSurfaceProps001 = 0x7308BB98;
    constexpr uint32_t rva_VPhysicsSurfaceProps001 = 0x18BB98;
    constexpr uint32_t VPhysicsCollision007 = 0x7307D24C;
    constexpr uint32_t rva_VPhysicsCollision007 = 0x17D24C;
    // Physics2_Interface_v0_4 = NULL (not instantiated)
    // Physics2_Interface_v0_3 = NULL (not instantiated)
    // Physics2_Disabler_Interface_v1 = NULL (not instantiated)
    // Physics2_Interface_v0_5 = NULL (not instantiated)
    constexpr uint32_t VPhysics031 = 0x7307D1CC;
    constexpr uint32_t rva_VPhysics031 = 0x17D1CC;
}

namespace vstdlib_dll {
    constexpr uint32_t VProcessUtils001 = 0x74A7A6E0;
    constexpr uint32_t rva_VProcessUtils001 = 0x2A6E0;
    constexpr uint32_t VEngineCvar007 = 0x74A7C0D0;
    constexpr uint32_t rva_VEngineCvar007 = 0x2C0D0;
}

} // namespace nulvex::interfaces
