#pragma once
// Generated by Nulvex L4D2 Dumper v6
// 2026-09-30 12:49:51

#include <cstdint>

namespace nulvex::dump {

namespace client_dll {
    constexpr uint32_t dwBase = 0x5D860000; // constant | module base address
    constexpr uint32_t dwSize = 0x963000; // constant | module size
    constexpr uint32_t dwEntityList = 0x5DFAA574; // exact_interface | VClientEntityList003 interface ptr
    constexpr uint32_t rvaEntityList = 0x74A574;
    constexpr uint32_t dwClientDll = 0x5DF24A98; // exact_interface | VClient016 interface ptr
    constexpr uint32_t rvaClientDll = 0x6C4A98;
    constexpr uint32_t dwGetAllClasses = 0x5D908A40; // exact_interface
    constexpr uint32_t rvaGetAllClasses = 0xA8A40;
    constexpr uint32_t dwClientClassHead = 0x5DF9A4D4; // exact_interface | ClientClass linked list
    constexpr uint32_t rvaClientClassHead = 0x73A4D4;
    constexpr uint32_t dwEntityArrayOffset = 0x20; // heuristic | offset from entity list ptr
    constexpr uint32_t nEntityStride = 0x10; // constant | CEntInfo stride (4 ptrs x 4 bytes)
    constexpr uint32_t nEntList_GetClientEntity = 0x3; // exact_interface | vtable index
    constexpr uint32_t nEntity_IClientNetworkable = 0x8; // constant | offset to IClientNetworkable vtbl ptr
    constexpr uint32_t nNetworkable_GetClientClass = 0x2; // constant | IClientNetworkable vtable index
    constexpr uint32_t kBaseShift = 0x88; // heuristic | entity ptr to RecvTable data start (score=79, 2nd=75, margin=4, 22 entities)
}

namespace d3d9_dll {
    constexpr uint32_t dwBase = 0x72A90000; // constant | module base address
    constexpr uint32_t dwSize = 0x171000; // constant | module size
    constexpr uint32_t nReset = 0x10; // constant | IDirect3DDevice9::Reset vtable index
    constexpr uint32_t nPresent = 0x11; // constant | IDirect3DDevice9::Present vtable index
    constexpr uint32_t nEndScene = 0x2A; // constant | IDirect3DDevice9::EndScene vtable index
    constexpr uint32_t nDrawIndexedPrimitive = 0x52; // constant
}

namespace engine_dll {
    constexpr uint32_t dwBase = 0x71060000; // constant | module base address
    constexpr uint32_t dwSize = 0x73F000; // constant | module size
    constexpr uint32_t ptrSignonState = 0xF1E0080; // runtime_validated | IN GAME (>=6)
    constexpr uint32_t ptrClientState = 0xF1E0018; // runtime_validated | CClientState heap ptr (signon confirmed)
    constexpr uint32_t dwLocalPlayer = 0x7148FFB8; // pattern_matched | vtbl[42] pattern (slot=7053 not in game?)
    constexpr uint32_t rvaLocalPlayer = 0x42FFB8;
    constexpr uint32_t nLocalPlayerDeref = 0xC; // exact_interface | offset within struct for player slot
    constexpr uint32_t ptrLocalPlayerSlot = 0xF1E0040; // runtime_validated | CClientState+0x28 = 1 (stable, heap-based)
    constexpr uint32_t nCsPlayerSlot = 0x28; // runtime_validated | CClientState offset for m_nPlayerSlot
    constexpr uint32_t dwMaxClients = 0x71487CC0; // pattern_matched | ptr, not count
    constexpr uint32_t rvaMaxClients = 0x427CC0;
    constexpr uint32_t dwGlobalVars = 0x714AA57C; // runtime_validated | CGlobalVarsBase*
    constexpr uint32_t rvaGlobalVars = 0x44A57C;
    constexpr uint32_t dwViewMatrix = 0x71661F9C; // runtime_validated | VP matrix (view-projection)
    constexpr uint32_t rvaViewMatrix = 0x601F9C;
    constexpr uint32_t dwRenderEngine = 0x71487BC0; // runtime_validated | render engine global ptr (VP matrix chain validated)
    constexpr uint32_t rvaRenderEngine = 0x427BC0;
    constexpr uint32_t nVtblWorldToScreen = 0x25; // exact_interface | vtbl[37] thunk -> render vtbl[13]
    constexpr uint32_t dwConVarHead = 0x71493BA8; // runtime_validated | ConVar linked list head (first: MZ )
    constexpr uint32_t rvaConVarHead = 0x433BA8;
    constexpr uint32_t nVtblIsInGame = 0x1A; // exact_interface | VEngineClient vtable index
    constexpr uint32_t nVtblGetLocalPlayer = 0x2A; // exact_interface
    constexpr uint32_t nVtblGetScreenSize = 0x5; // exact_interface
    constexpr uint32_t nVtblGetMaxClients = 0x2B; // exact_interface | returns ptr, not count
}

namespace inputsystem_dll {
    constexpr uint32_t dwBase = 0x749C0000; // constant | module base address
    constexpr uint32_t dwSize = 0x28000; // constant | module size
}

namespace left4dead2_exe {
    constexpr uint32_t dwBase = 0xD30000; // constant | module base address
    constexpr uint32_t dwSize = 0x5E000; // constant | module size
}

namespace materialsystem_dll {
    constexpr uint32_t dwBase = 0x74880000; // constant | module base address
    constexpr uint32_t dwSize = 0x13D000; // constant | module size
}

namespace server_dll {
    constexpr uint32_t dwBase = 0x5CED0000; // constant | module base address
    constexpr uint32_t dwSize = 0x982000; // constant | module size
}

namespace shaderapidx9_dll {
    constexpr uint32_t dwBase = 0x72C10000; // constant | module base address
    constexpr uint32_t dwSize = 0xFF000; // constant | module size
}

namespace studiorender_dll {
    constexpr uint32_t dwBase = 0x74250000; // constant | module base address
    constexpr uint32_t dwSize = 0x453000; // constant | module size
}

namespace tier0_dll {
    constexpr uint32_t dwBase = 0x74AF0000; // constant | module base address
    constexpr uint32_t dwSize = 0x7C000; // constant | module size
}

namespace vguimatsurface_dll {
    constexpr uint32_t dwBase = 0x72D80000; // constant | module base address
    constexpr uint32_t dwSize = 0x172000; // constant | module size
}

namespace vphysics_dll {
    constexpr uint32_t dwBase = 0x72F00000; // constant | module base address
    constexpr uint32_t dwSize = 0x1B5000; // constant | module size
}

namespace vstdlib_dll {
    constexpr uint32_t dwBase = 0x74A50000; // constant | module base address
    constexpr uint32_t dwSize = 0x9A000; // constant | module size
}

} // namespace nulvex::dump
